Refactor
Teaching-projects/SZE-MOSZE-2020-Daemons pull request #12
Opened 2020-11-03 17:06 UTC by Lazar-source

@hegyhati  Megcsináltuk a kért változtatásokat a branchen.

2020-11-04 17:02 UTC, hegyhati requested changes

2020-11-04 17:02 UTC, hegyhati commented on JSON.h
> +  }
Ez egy T=int-re nagyon csunyan elhasal

2020-11-04 17:02 UTC, hegyhati commented on Hero.cpp
> +	std::stod(returnedMap.get<std::string>("cooldown_multiplier_per_level"))
na pont ezekre az sto*-kra nem lenne szukseg, ha a a get rendesen meg lenne irva.

2020-11-04 19:48 UTC, Lazar-source commented
@hegyhati  Kijavitottuk a kért változtatásokat, variantot használ a program.

2020-11-06 12:14 UTC, hegyhati approved these changes

2020-11-06 12:14 UTC, merged