Prepared game
Teaching-projects/SZE-MOSZE-2020-Daemons pull request #20
Opened 2020-12-02 17:07 UTC by mesmatyi

2020-12-02 17:25 UTC, mesmatyi commented
Elkészült a PreparedGame

2020-12-02 19:08 UTC, rolandborbely requested changes

2020-12-02 19:08 UTC, rolandborbely commented on Game.cpp
> +    monsters_of.push_back(remakredmap.get<std::string>("monster-3"));
tegyük fel, hogy a scenario fájlban monster-5 van, akkor nem fog lefutni a program

2020-12-02 19:08 UTC, rolandborbely commented on test/all_unittests.cpp
> -}
ezért sem kellene protectednek lenni a put függvényeknek szerintem

2020-12-02 19:08 UTC, rolandborbely commented on Game.h
> +    void putMonster(Monster monster,int x, int y);
Ezeknek szerintem publicnak kellene lenni. Így ha sima game-t akarunk inditani, akkor nem fogunk tudni herot meg monstereket felrakni. PreparedGame-ben viszont tényleg nem szabad látszódniuk.
mappal ugyanez

2020-12-02 20:20 UTC, mesmatyi commented
@rolandborbely javítottam

2020-12-02 20:21 UTC, rolandborbely approved these changes

2020-12-02 20:45 UTC, mesmatyi commented
@Lazar-source  conflictok feloldva

2020-12-03 08:16 UTC, Lazar-source approved these changes

2020-12-03 08:16 UTC, merged