Rendering
Teaching-projects/SZE-MOSZE-2020-Daemons pull request #22
Opened 2020-12-05 17:44 UTC by kulcsarbence

Elkészítettük a rendering branchet.

2020-12-05 17:45 UTC, kulcsarbence commented
@petinexus kész a renderer branch

2020-12-05 22:39 UTC, petinexus requested changes

2020-12-05 22:39 UTC, petinexus commented on CharacterSVGRenderer.cpp
> +    //std::string svg_output = gm.mapPrinterSVGWithLightRadius();
Ilyen ne maradjon benne.

2020-12-05 22:39 UTC, petinexus commented on CharacterSVGRenderer.h
> +    private:
Ez itt nincs használva.

2020-12-05 22:39 UTC, petinexus commented on Game.cpp
> +    //mapPrinter();
Kommenteket akkor szedd ki légy szíves. Nem jelölgetem őket külön.

2020-12-06 08:36 UTC, rolandborbely requested changes
ha unit test nem is készül erre, legalább az egyik svg legyen diffelve

2020-12-06 08:36 UTC, rolandborbely commented on Main.cpp
>      } catch (const JSON::ParseException& e) {bad_exit(4);}
ide raknék be még catcheket, mivel így csak a ParserExceptiont kapja el, a többi fajtát nem

2020-12-06 08:36 UTC, rolandborbely commented on Makefile
> +CharacterSVGRenderer.o: CharacterSVGRenderer.h Renderer.h
makefile-ban dependency-nek az összes headert meg kell adni, amit használ, pl. a TextRenderernél Render, Game, Monster, Hero, Map és így tovább
ez mindegyik .o targetnél

2020-12-06 08:43 UTC, kulcsarbence commented on CharacterSVGRenderer.h
> +    private:
Javitva

2020-12-06 08:43 UTC, kulcsarbence commented on Game.cpp
> +    //mapPrinter();
Javitva

2020-12-06 08:44 UTC, kulcsarbence commented on CharacterSVGRenderer.cpp
> +    //std::string svg_output = gm.mapPrinterSVGWithLightRadius();
Javitva

2020-12-06 10:29 UTC, rolandborbely approved these changes

2020-12-06 10:31 UTC, petinexus requested changes

2020-12-06 10:31 UTC, petinexus commented on CharacterSVGRenderer.cpp
> +    std::string wall_field_svg = "wall_field.svg";
A falat és a szabad területet a json fájlból kell beolvasni, ezt javítsátok légy szíves.

2020-12-06 10:31 UTC, petinexus commented on CharacterSVGRenderer.cpp
> +    std::string free_field_svg = "free_field.svg";
.

2020-12-06 11:26 UTC, Lazar-source commented
@petinexus  elvileg megvannak a kért változtatások

2020-12-06 11:49 UTC, petinexus approved these changes

2020-12-06 11:58 UTC, Lazar-source approved these changes

2020-12-06 11:58 UTC, merged