Documentation
Teaching-projects/SZE-MOSZE-2020-Daemons pull request #9
Opened 2020-10-26 19:11 UTC by Lazar-source

Dokumentáció kiegészítve

2020-10-26 19:21 UTC, petinexus commented on .github/workflows/Documentation.yml
>        - gh-pages
Ez ide nem kell.

2020-10-26 19:23 UTC, petinexus commented on .github/workflows/Documentation.yml
>        - gh-pages
gh-pages töröljétek innen.

2020-10-26 19:28 UTC, rolandborbely requested changes
Pár dolog van, ami szerintem nem jó

2020-10-26 19:28 UTC, rolandborbely commented on .github/workflows/Documentation.yml
> +      - documentation
itt a master branch kell szerintem, hogy az alapján buildelje le az oldalt

2020-10-26 19:28 UTC, rolandborbely commented on .github/workflows/Documentation.yml
>        - gh-pages
a gh-pages felesleges ide, ott nincs semmi, ami alapján a doxygen generálni tud valamit

2020-10-26 19:28 UTC, rolandborbely commented on JsonParser.h
> +	*/
innen hiányzik a return szerintem

2020-10-26 19:30 UTC, petinexus requested changes

2020-10-26 19:30 UTC, petinexus commented on .github/workflows/Documentation.yml
>        - gh-pages
Ez ide nem kell. gh-pages töröljétek.

2020-10-26 19:30 UTC, petinexus commented on .github/workflows/Documentation.yml
> +      - documentation
Szerintem csak a master alapján buildeljen. Cseréljétek.

2020-10-27 11:29 UTC, Lazar-source commented
A kért változtatások készen vannak.

2020-10-27 11:30 UTC, rolandborbely approved these changes

2020-10-27 11:31 UTC, mesmatyi approved these changes

2020-10-27 11:36 UTC, petinexus approved these changes

2020-10-27 11:45 UTC, merged